sudo: required
services:
	- docker
before_install:
	- docker build -t hamzamirza/docker-react-app-image -f dockerfile.dev .
script:
	- docker run  hamzamirza/docker-react-app-image npm run test -- --coverage
