--- 
before_install: 
  - "docker build -t hamzamirza/docker-react-app-image -f dockerfile.dev ."
script: 
  - "docker run -e CI=true hamzamirza/docker-react-app-image npm run test"
services: 
  - docker
sudo: required

